version: '3'
service:
  server:
    image: php:7.4-apache
    ports: 8080:8080
    volumes: 
      - ./back:/var/www/html
    depends_on: 
      - db
  db:
    image: mysql:5.7
    enviroment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbe_bd
    ports:
      3306:3306
    volumes:
      - ./back/db:/var/lib/mysql
    